[package]
name = "aoc_runner"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
aoc = { path = "../aoc" }
year_2023 = { path = "../year_2023" }
year_2024 = { path = "../year_2024" }

[[bin]]
path = "main.rs"
name = "aoc_runner"
